### ISSUE TITLE
Freshy cloned copy is broken. Any ideas?

### ISSUE THREAD

**Issue by ximbal** [piral-samples/sample-piral-ssr#1]
Just cloned the repo for testing, got this error trace:

> $ npm i && npm run build && npm start
> 
> > fsevents@1.2.9 install /Users/en/Development/explorations/sample-piral-ssr/node_modules/fsevents
> > node install
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download
> node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v79-darwin-x64.tar.gz
> node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@13.1.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
>   SOLINK_MODULE(target) Release/.node
>   CXX(target) Release/obj.target/fse/fsevents.o
>   SOLINK_MODULE(target) Release/fse.node
>   COPY /Users/en/Development/explorations/sample-piral-ssr/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node
>   TOUCH Release/obj.target/action_after_build.stamp
> 
> > deasync@0.1.16 install /Users/en/Development/explorations/sample-piral-ssr/node_modules/deasync
> > node ./build.js
> 
> `darwin-x64-node-13` exists; testing
> Binary is fine; exiting
> 
> > core-js@2.6.10 postinstall /Users/en/Development/explorations/sample-piral-ssr/node_modules/core-js
> > node postinstall || echo "ignore"
> 
> Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
> 
> The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> > https://opencollective.com/core-js
> > https://www.patreon.com/zloirock
> 
> Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
> 
> 
> > parcel-bundler@1.12.4 postinstall /Users/en/Development/explorations/sample-piral-ssr/node_modules/parcel-bundler
> > node -e "console.log('\u001b[35m\u001b[1mLove Parcel? You can now donate to our open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/parcel/donate\u001b[0m')"
> 
> Love Parcel? You can now donate to our open collective:
>  > https://opencollective.com/parcel/donate
> added 872 packages from 676 contributors and audited 8708 packages in 18.31s
> found 0 vulnerabilities
> 
> 
> > sample-piral-ssr@1.0.0 build /Users/en/Development/explorations/sample-piral-ssr
> > parcel build src/client/index.tsx
> 
> ✨  Built in 6.22s.
> 
> dist/index.js.map    558.15 KB     58ms
> dist/index.js        220.48 KB    6.12s
> 
> 
>    ╭────────────────────────────────────────────────────────────────╮
>    │                                                                │
>    │      New minor version of npm available! 6.12.1 → 6.13.1       │
>    │   Changelog: https://github.com/npm/cli/releases/tag/v6.13.1   │
>    │               Run npm install -g npm to update!                │
>    │                                                                │
>    ╰────────────────────────────────────────────────────────────────╯
> 
> 
> > sample-piral-ssr@1.0.0 start /Users/en/Development/explorations/sample-piral-ssr
> > ts-node src/server/index.ts
> 
> Server running at port 3000.
> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
>     in ResponsiveLayout
>     in Context.Provider
>     in Piral
> (node:60201) UnhandledPromiseRejectionWarning: ReferenceError: matchMedia is not defined
>     at /Users/en/Development/explorations/sample-piral-ssr/node_modules/piral-core/src/utils/media.ts:8:57
>     at Array.findIndex (<anonymous>)
>     at Object.getCurrentLayout (/Users/en/Development/explorations/sample-piral-ssr/node_modules/piral-core/src/utils/media.ts:8:29)
>     at match (/Users/en/Development/explorations/sample-piral-ssr/node_modules/piral-core/src/hooks/media.ts:11:23)
>     at useReducer (/Users/en/Development/explorations/sample-piral-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:1335:57)
>     at Object.useState (/Users/en/Development/explorations/sample-piral-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:1273:10)
>     at Object.useState (/Users/en/Development/explorations/sample-piral-ssr/node_modules/react/cjs/react.development.js:1619:21)
>     at Object.useMedia (/Users/en/Development/explorations/sample-piral-ssr/node_modules/piral-core/src/hooks/media.ts:12:27)
>     at ResponsiveLayout (/Users/en/Development/explorations/sample-piral-ssr/node_modules/piral-core/src/components/ResponsiveLayout.tsx:13:20)
>     at processChild (/Users/en/Development/explorations/sample-piral-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3204:14)
> (node:60201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:60201) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
>     in ResponsiveLayout
>     in Context.Provider
>     in Piral
> (node:60201) UnhandledPromiseRejectionWarning: ReferenceError: matchMedia is not defined
>     at /Users/en/Development/explorations/sample-piral-ssr/node_modules/piral-core/src/utils/media.ts:8:57
>     at Array.findIndex (<anonymous>)
>     at Object.getCurrentLayout (/Users/en/Development/explorations/sample-piral-ssr/node_modules/piral-core/src/utils/media.ts:8:29)
>     at match (/Users/en/Development/explorations/sample-piral-ssr/node_modules/piral-core/src/hooks/media.ts:11:23)
>     at useReducer (/Users/en/Development/explorations/sample-piral-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:1335:57)
>     at Object.useState (/Users/en/Development/explorations/sample-piral-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:1273:10)
>     at Object.useState (/Users/en/Development/explorations/sample-piral-ssr/node_modules/react/cjs/react.development.js:1619:21)
>     at Object.useMedia (/Users/en/Development/explorations/sample-piral-ssr/node_modules/piral-core/src/hooks/media.ts:12:27)
>     at ResponsiveLayout (/Users/en/Development/explorations/sample-piral-ssr/node_modules/piral-core/src/components/ResponsiveLayout.tsx:13:20)
>     at processChild (/Users/en/Development/explorations/sample-piral-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3204:14)
> (node:60201) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)

lab:~/Development/explorations/sample-piral-ssr$ npm --version
6.12.1
lab:~/Development/explorations/sample-piral-ssr$ node --version
v13.1.0

Any ideas would be greatly appreciated

**Comment by FlorianRappl** [comment]
Sorry this is WIP right now (I changed sources in `node_modules` while developing it).

A fresh preview build of `piral-cli`, `piral-ssr-utils` etc. is on the way. I'll update the repo, clone again and if it works for me - I'd kindly ask you to try again.

Thanks for your patience and sorry for the inconvenience! :beers:

**Comment by ximbal** [comment]
Sounds like a plan, appreciated.

**Comment by FlorianRappl** [comment]
Updated and should work. cc @ximbal 

**Note**: The development warning regarding the `useLayoutEffect` hook should be ignored for the moment. We'll tidy this up before releasing the final 0.9 of Piral.

Feedback would be appreciated :beers:!

**Comment by ximbal** [comment]
Fix worked like a charm. Thank you!
