### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by daviddang91** [piral-samples/sample-piral-ssr#17]
Hello,
I get an error when I try to run this project. Do you know how to fix it?
- Os: macOS Monterey 12.0.1
- Node version: 8.0.0
- Command: `npm i && npm run build && npm start`

> (node:3340) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): SyntaxError: Unexpected token ...
> (node:3340) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> sample-piral-ssr@1.0.1 start /Users/username/gitlab/example/sample-piral-ssr
> ts-node src/server/index.ts
> 
> 
> /Users/username/gitlab/example/sample-piral-ssr/node_modules/piral-core/src/modules/api.ts:12
> if ('customElements' in window) {
>                         ^
> ReferenceError: window is not defined
>     at Object.<anonymous> (/Users/username/gitlab/example/sample-piral-ssr/node_modules/piral-core/src/modules/api.ts:12:25)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/Users/username/gitlab/example/sample-piral-ssr/node_modules/piral-core/src/modules/index.ts:1:1)
>     at Module._compile (module.js:569:30)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! sample-piral-ssr@1.0.1 start: `ts-node src/server/index.ts`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the sample-piral-ssr@1.0.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/username/.npm/_logs/2021-11-24T02_21_59_786Z-debug.log

**Comment by FlorianRappl** [comment]
Yes, just update to the latest version of `piral`!

**Comment by FlorianRappl** [comment]
I've updated the package.json.

**Comment by daviddang91** [comment]
It worked. Thanks
