### ISSUE TITLE
Error load image on the server side

### ISSUE THREAD

**Issue by daviddang91** [piral-samples/sample-piral-ssr#18]
Hello,

I'm trying to add an image to this project, but it can not load that image.

I created an images folder inside the common folder and push an image into it. I'm using that image as below:
> <img src={require('./images/minion.jpeg')} height="200px"/ >

I did run the command `yarn build` before access to localhost:3000 to test. But I still get errors below:

> $ ts-node src/server/index.ts
> Server running at port 3000.
> /Users/username/gitlab/example/sample-piral-ssr/src/common/images/minion.jpeg:1
> ����
> 
> 
> SyntaxError: Invalid or unexpected token
>     at Object.compileFunction (node:vm:352:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1031:15)
>     at Module._compile (node:internal/modules/cjs/loader:1065:27)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Layout (/Users/username/gitlab/example/sample-piral-ssr/src/common/instance.tsx:16:25)
>     at processChild (/Users/username/gitlab/example/sample-piral-ssr/node_modules/react-dom/cjs/react-dom-server.node.development.js:3043:14)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by FlorianRappl** [comment]
I've added the `registerAssetResolver` utility to resolve that in the example.

The given part has nothing to do with Piral (hence it was included in the example). You'll need an (isomorphic) way of handling resources / asset URLs. I've chosen to resolve the image to its generated asset (doing that resolution using Webpack's manifest, other bundlers have similar concepts).

Hope that helps!
